name: Enhancement
description: What feature would you like added to the software?
title: "[Enhancement]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: What are your suggestions?
      placeholder: Tell us what you would like!
    validations:
      required: true